<#
.SYNOPSIS
    One-time setup: creates 'callisto-ddns' Azure AD service principal scoped
    to the rhombus.rocks DNS zone, writes credentials to
    $env:LOCALAPPDATA\azure-ddns\env, and registers the Task Scheduler job.

.DESCRIPTION
    Mirrors the design of phase-3-arch-postinstall/setup-azure-ddns.sh on the
    Linux side, but as a Windows-native PowerShell script. Uses the Az
    PowerShell module for SP / role-assignment creation (no Azure CLI).

    Idempotent: re-running rotates the SP secret (existing one is invalidated)
    and rewrites the env file. The role assignment is created once and skipped
    on subsequent runs.

    Locked config below comes from the project's metis-ddns setup, with
    callisto-specific overrides (SP name + record name).
#>
[CmdletBinding()]
param(
    [string]$EnvFile      = (Join-Path $env:LOCALAPPDATA 'azure-ddns\env'),
    [string]$TaskXmlPath  = "$PSScriptRoot\..\task-scheduler\Update Azure DDNS.xml",
    [switch]$SkipTask
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version 3.0

# ---- Locked config (same tenant/sub/zone as Linux metis-ddns) ----------
$TenantId       = 'bb462d15-cc1e-4a17-b0db-3ba7fcd00b21'  # Butler Software LLC
$SubscriptionId = 'ab78414a-6bf4-4d87-b27c-954c41aa8081'
$ResourceGroup  = 'rhombus'
$DnsZone        = 'rhombus.rocks'
$RecordName     = 'callisto'
$SpDisplayName  = 'callisto-ddns'

function Log  { param([string]$M) Write-Host "[+] $M" -ForegroundColor Cyan }
function Warn { param([string]$M) Write-Warning $M }

# ---- Connect to Azure ---------------------------------------------------
$ctx = Get-AzContext -ErrorAction SilentlyContinue
if (-not $ctx -or $ctx.Tenant.Id -ne $TenantId) {
    Log "Connecting to Azure tenant $TenantId (browser will pop)..."
    Connect-AzAccount -Tenant $TenantId -Subscription $SubscriptionId | Out-Null
    $ctx = Get-AzContext
}
if ($ctx.Subscription.Id -ne $SubscriptionId) {
    Set-AzContext -SubscriptionId $SubscriptionId | Out-Null
}
Log "Tenant:   $TenantId"
Log "Sub:      $SubscriptionId"

# ---- Verify DNS zone exists -------------------------------------------
$zone = Get-AzDnsZone -ResourceGroupName $ResourceGroup -Name $DnsZone -ErrorAction SilentlyContinue
if (-not $zone) { throw "DNS zone '$DnsZone' not found in resource group '$ResourceGroup'" }
$zoneScope = "/subscriptions/$SubscriptionId/resourceGroups/$ResourceGroup/providers/Microsoft.Network/dnszones/$DnsZone"

# ---- App registration --------------------------------------------------
$existing = Get-AzADApplication -DisplayName $SpDisplayName -ErrorAction SilentlyContinue | Select-Object -First 1
if ($existing) {
    Log "Reusing existing app '$SpDisplayName' (appId=$($existing.AppId))"
    $appId = $existing.AppId
} else {
    Log "Creating app registration '$SpDisplayName'..."
    $app = New-AzADApplication -DisplayName $SpDisplayName
    $appId = $app.AppId
    # SP creation isn't automatic with New-AzADApplication.
    New-AzADServicePrincipal -ApplicationId $appId | Out-Null
}

$sp = Get-AzADServicePrincipal -ApplicationId $appId
if (-not $sp) {
    Log "Creating service principal for $appId..."
    $sp = New-AzADServicePrincipal -ApplicationId $appId
}

# ---- Rotate secret (REPLACES — old one invalidated) -------------------
Log "Rotating secret (default 1y)..."
# Wipe all existing passwords first so this is truly idempotent.
Get-AzADAppCredential -ApplicationId $appId | ForEach-Object {
    Remove-AzADAppCredential -ApplicationId $appId -KeyId $_.KeyId -ErrorAction SilentlyContinue
}
$end = (Get-Date).AddYears(1)
$cred = New-AzADAppCredential -ApplicationId $appId -EndDate $end
$clientSecret = $cred.SecretText
if (-not $clientSecret) { throw "credential creation returned no SecretText" }

# ---- Role assignment ---------------------------------------------------
Log "Ensuring DNS Zone Contributor on $DnsZone..."
$existingRole = Get-AzRoleAssignment -ObjectId $sp.Id -Scope $zoneScope -RoleDefinitionName 'DNS Zone Contributor' -ErrorAction SilentlyContinue
if (-not $existingRole) {
    # Role assignments can fail with "principal not found" if the SP hasn't
    # propagated yet — retry a couple of times.
    for ($i = 0; $i -lt 6; $i++) {
        try {
            New-AzRoleAssignment -ObjectId $sp.Id -RoleDefinitionName 'DNS Zone Contributor' -Scope $zoneScope | Out-Null
            break
        } catch {
            if ($i -eq 5) { throw }
            Start-Sleep -Seconds 5
        }
    }
} else {
    Log "  (role assignment already exists — fine)"
}

# ---- Write env file (user-only ACL) ------------------------------------
$envDir = Split-Path -Parent $EnvFile
New-Item -ItemType Directory -Path $envDir -Force | Out-Null

$envContent = @"
# Generated by setup-azure-ddns.ps1 on $(Get-Date -Format 'yyyy-MM-ddTHH:mm:sszzz')
# Re-run that script to rotate the secret (old one is invalidated automatically).
AZURE_TENANT_ID=$TenantId
AZURE_CLIENT_ID=$appId
AZURE_CLIENT_SECRET=$clientSecret
AZURE_SUBSCRIPTION_ID=$SubscriptionId
AZURE_RESOURCE_GROUP=$ResourceGroup
AZURE_DNS_ZONE=$DnsZone
AZURE_DNS_RECORD=$RecordName
AZURE_DNS_TTL=300

# IPv6-only on this host (router does CG-NAT v4, no point publishing the gateway).
AZURE_DDNS_DISABLE_IPV4=1
AZURE_DDNS_DISABLE_IPV6=0

# Source selection — pin to the kernel-managed stable SLAAC GUA. Without
# this, Windows source-address selection would prefer the RFC 4941
# temporary address (rotates ~24h, would churn DNS). See
# update-azure-ddns.ps1 header for the full mode list.
AZURE_DDNS_IPV6_SELECT=stable
"@

Set-Content -LiteralPath $EnvFile -Value $envContent -Encoding utf8 -NoNewline

# Lock the env file: disable inheritance, grant FullControl to current user only.
$acl = Get-Acl -LiteralPath $EnvFile
$acl.SetAccessRuleProtection($true, $false)
$rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
    [System.Security.Principal.WindowsIdentity]::GetCurrent().User,
    'FullControl', 'Allow')
$acl.SetAccessRule($rule)
Set-Acl -LiteralPath $EnvFile -AclObject $acl

Log "Wrote $EnvFile (user-only ACL)"

# ---- Register scheduled task ------------------------------------------
if (-not $SkipTask -and (Test-Path -LiteralPath $TaskXmlPath)) {
    Log "Registering Task Scheduler job from $TaskXmlPath..."
    $taskName = '\Rhombus\Update Azure DDNS'
    schtasks.exe /Delete /TN $taskName /F 2>&1 | Out-Null
    schtasks.exe /Create /TN $taskName /XML "$TaskXmlPath" /F | Out-Null
    Log "Task registered. Kicking off first run..."
    Start-ScheduledTask -TaskName 'Update Azure DDNS' -TaskPath '\Rhombus\'
    Start-Sleep 3
    schtasks.exe /Query /TN $taskName /V /FO LIST | Select-String 'Last Run|Last Result|Status' | ForEach-Object { Write-Host "  $_" }
}

# ---- Report -----------------------------------------------------------
Write-Host ""
Log "Azure DDNS wired. Summary:"
Write-Host "  Tenant:      $TenantId"
Write-Host "  App / SP:    $appId  ($SpDisplayName)"
Write-Host "  Scope:       $DnsZone in resource group $ResourceGroup"
Write-Host "  Record:      $RecordName.$DnsZone  AAAA (next ddns run will populate)"
Write-Host "  Secret life: 1 year (rotate by re-running this script)"
Write-Host "  Env file:    $EnvFile"
Write-Host ""
Write-Host "Verify externally:"
Write-Host "  Resolve-DnsName $RecordName.$DnsZone -Type AAAA -Server 1.1.1.1"
